# Generated by Django 5.2.6 on 2025-11-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGDReviews', '0004_review_rating_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='genres',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
