# Generated by Django 5.2.6 on 2025-12-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGDReviews', '0005_review_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='game_id',
            field=models.IntegerField(default=0),
        ),
    ]
